### ISSUE TITLE
two led strips

### ISSUE THREAD

**Issue by VOVAiS** [stelioskat/esp8266-led-dimmer#1]
Hello. 
Can version of your sketch in two led strips?

**Comment by stelioskat** [comment]
Hi. Do you mean to drive them individually or just connect them in parallel?

**Comment by VOVAiS** [comment]
drive them individually

**Comment by stelioskat** [comment]
this would require a second transistor. You could e.g. replicate in GPIO5 the same exactly circuitry as you can see at GPIO4. Of course you would have to extend the firmware accordingly and ensure that your power supply (VCC) has enough power.
