### ISSUE TITLE
Connect to MQTT Broker with username and password

### ISSUE THREAD

**Issue by ghost** [stelioskat/esp8266-led-dimmer#2]
How can i enter my username and password for my MQTT Broker in the sketch?

**Comment by stelioskat** [comment]
Hey @TimMakes ! Check out the  [Adafruit MQTT lib](https://github.com/adafruit/Adafruit_MQTT_Library/blob/master/Adafruit_MQTT_Client.h) it has two optional parameters for this:

`Adafruit_MQTT_Client(Client *client, const char *server, uint16_t port,
                       const char *user="", const char *pass="")`
